services:
  streamlit:
    build: .
    container_name: streamlit
    command: streamlit hello --server.port=${STREAMLIT_PORT} --server.address=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "${STREAMLIT_PORT}:${STREAMLIT_PORT}"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  jupyter:
    build: .
    container_name: jupyter
    command: jupyter lab --ip=0.0.0.0 --port=${JUPYTER_PORT} --no-browser --allow-root
    volumes:
      - .:/app
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    restart: unless-stopped
